media_folder: "src/uploads/images" # Location where files will be stored in the repo
public_folder: "src/uploads/images" # The src attribute for uploaded media
backend:
  name: git-gateway
  branch: decap # Branch to update (optional; defaults to master)
collections:
  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "News" # Used in the UI
    folder: "src/content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{slug}}"
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
      - label: "Featured Image"
        name: "image"
        widget: "object"
        fields:
          - { label: "Image", name: "url", widget: "image"}
          - { label: "Description", name: "alt", widget: "string", hint: "Briefly describe the image for the benefit of the visually impaired"}
      - { label: "Link", name: "link", widget: "string", hint: "Full URL for the source of the news" }
      - { label: "Source Name", name: "sourceName", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown" }